AWSTemplateFormatVersion: '2010-09-09'
Description: Simple Amazon EC2 Instance

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    Description: EC2 instance type

Resources:
  MinhaInstancia:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0ed9277fb7eb570c9
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: EC2

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MinhaInstancia
