AWSTemplateFormatVersion: '2010-09-09'
Description: EC2, S3 Bucket, IAM User and Group

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    Description: EC2 instance type
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-foundation

  IAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: gpo-admin-lab

  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: alexsandro.lechner
      Groups:
        - !Ref IAMGroup

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c55b159cbfafe1f0
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          apt-get install -y python3-pip

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
  IAMUserName:
    Description: IAM User Name
    Value: !Ref IAMUser
